# ATTENTION: Adobe does not provide support for the npm-publish action. We show it here
# as an example only. Please see the README at https://github.com/pascalgn/npm-publish-action
# for full instructions and information on the action.
#
# When used in a repo under the github.com/adobe organization, repo maintainers should
# contact Adobe's Open Source Office to gain access to the secrets.ADOBE_BOT_NPM_TOKEN.
name: npm-publish
on:
  workflow_dispatch:

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Clean npm cache and node_modules
      run: |
        rm -rf node_modules
        npm cache clean --force

    - name: Install dependencies
      run: |
        npm ci
        npm install @rollup/rollup-linux-x64-gnu --save-dev

    - name: Build packages
      run: npm run build --workspaces

    - name: Publish NodeJS SDK
      uses: JS-DevTools/npm-publish@v3
      with:
        package: packages/sdk-nodejs
        token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
        registry: https://registry.npmjs.org/
        access: public
        tag: latest
        strategy: upgrade
        ignore-scripts: true
        dry-run: false

    - name: Publish Akamai SDK
      uses: JS-DevTools/npm-publish@v3
      with:
        package: packages/sdk-akamai
        token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
        registry: https://registry.npmjs.org/
        access: public
        tag: latest
        strategy: upgrade
        ignore-scripts: true
        dry-run: false
